/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PublicIndexRouteImport } from './routes/public/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks/index'
import { Route as DashboardNewRouteImport } from './routes/dashboard/new'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PublicPromptIdIndexRouteImport } from './routes/public/$promptId/index'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as DashboardPromptIdIndexRouteImport } from './routes/dashboard/$promptId/index'
import { Route as DashboardPromptIdEditRouteImport } from './routes/dashboard/$promptId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/dashboard/new',
  path: '/dashboard/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPromptIdIndexRoute = PublicPromptIdIndexRouteImport.update({
  id: '/public/$promptId/',
  path: '/public/$promptId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPromptIdIndexRoute = DashboardPromptIdIndexRouteImport.update({
  id: '/dashboard/$promptId/',
  path: '/dashboard/$promptId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPromptIdEditRoute = DashboardPromptIdEditRouteImport.update({
  id: '/dashboard/$promptId/edit',
  path: '/dashboard/$promptId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/public/': typeof PublicIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/$promptId/edit': typeof DashboardPromptIdEditRoute
  '/dashboard/$promptId/': typeof DashboardPromptIdIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/public/$promptId/': typeof PublicPromptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/public': typeof PublicIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/$promptId/edit': typeof DashboardPromptIdEditRoute
  '/dashboard/$promptId': typeof DashboardPromptIdIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/public/$promptId': typeof PublicPromptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/public/': typeof PublicIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/$promptId/edit': typeof DashboardPromptIdEditRoute
  '/dashboard/$promptId/': typeof DashboardPromptIdIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/public/$promptId/': typeof PublicPromptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/new'
    | '/bookmarks/'
    | '/dashboard/'
    | '/notifications/'
    | '/public/'
    | '/settings/'
    | '/dashboard/$promptId/edit'
    | '/dashboard/$promptId/'
    | '/profile/$userId/'
    | '/public/$promptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/new'
    | '/bookmarks'
    | '/dashboard'
    | '/notifications'
    | '/public'
    | '/settings'
    | '/dashboard/$promptId/edit'
    | '/dashboard/$promptId'
    | '/profile/$userId'
    | '/public/$promptId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/new'
    | '/bookmarks/'
    | '/dashboard/'
    | '/notifications/'
    | '/public/'
    | '/settings/'
    | '/dashboard/$promptId/edit'
    | '/dashboard/$promptId/'
    | '/profile/$userId/'
    | '/public/$promptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardNewRoute: typeof DashboardNewRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PublicIndexRoute: typeof PublicIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  DashboardPromptIdEditRoute: typeof DashboardPromptIdEditRoute
  DashboardPromptIdIndexRoute: typeof DashboardPromptIdIndexRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
  PublicPromptIdIndexRoute: typeof PublicPromptIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/public'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/dashboard/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$promptId/': {
      id: '/public/$promptId/'
      path: '/public/$promptId'
      fullPath: '/public/$promptId/'
      preLoaderRoute: typeof PublicPromptIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$promptId/': {
      id: '/dashboard/$promptId/'
      path: '/dashboard/$promptId'
      fullPath: '/dashboard/$promptId/'
      preLoaderRoute: typeof DashboardPromptIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$promptId/edit': {
      id: '/dashboard/$promptId/edit'
      path: '/dashboard/$promptId/edit'
      fullPath: '/dashboard/$promptId/edit'
      preLoaderRoute: typeof DashboardPromptIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardNewRoute: DashboardNewRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PublicIndexRoute: PublicIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  DashboardPromptIdEditRoute: DashboardPromptIdEditRoute,
  DashboardPromptIdIndexRoute: DashboardPromptIdIndexRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
  PublicPromptIdIndexRoute: PublicPromptIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
